### ISSUE TITLE
Developmental Editor @Ploomber

### ISSUE THREAD

**Issue by balapriyac** [ploomber/contributing#1]
Hi Eduardo,
I'd like to be a _Developmental Editor_ at Ploomber. I can suggest edits on structure, readability, and overall content of the blog posts and tutorials.

Best.
Bala

**Comment by edublancas** [comment]
Awesome! We could definitely use some help with the introductory tutorials, to ensure they're clear.

Example: https://docs.ploomber.io/en/latest/get-started/basic-concepts.html

The source code is here: https://github.com/ploomber/ploomber/blob/master/doc/get-started/basic-concepts.rst

Please fork the repo and open a PR with your suggestions!

Since you'll be contributing to the docs, there's no need to configure anything, you can just fork and edit from GitHub directly.

Let me know if you have questions!

**Comment by balapriyac** [comment]
Thank you @edublancas, I'll take a look and reach out to you if I have queries.

**Comment by edublancas** [comment]
awesome!

**Comment by edublancas** [comment]
I'm closing this since I saw you opened a PR. Thanks a lot for contributing!
