### ISSUE TITLE
Conflicts Bot

### ISSUE THREAD

**Issue by idomic** [ploomber/contributing#16]
We need a bot to notify the originator about conflicts with master (solve the conflicts if possible via main rebase).
This is relevant to all of the packages.

**Comment by edublancas** [comment]
did some research on this, we can configure GitHub to send alerts when a PR has conflicts ([see here](https://github.com/isaacs/github/issues/224#issuecomment-705628332)), there is a second unofficial [alternative](https://github.com/isaacs/github/issues/224#issuecomment-857554735).

I already configured GitHub to send me alerts (it looks like everyone has to configure their accounts since this sends a private message). Let's give it a try; I'd instead stick with the official solution. If we like it, then we can make it official and document it in this repo.

wanna test it as well? @neelasha23

**Comment by edublancas** [comment]
Today I got the scheduled reminder for this; it works great for me. Here's how to activate it:

[Go to reminders.](https://github.com/settings/reminders), and click on the Ploomber organization. Then, connect to our Slack workspace and enable notifications for PRs with conflicts, then configure the reminders.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/989250/215758478-465046b1-9039-4c3b-94ea-e0b1f34c1ee8.png">

**Comment by marc-hb** [comment]
@edublancas can you confirm you found no alternative without Slack or other third-party software?

**Comment by edublancas** [comment]
@marc-hb: we use Slack for team communication so we stopped looking for alternatives, it's been working well so far
